name: memogenerator
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_lints: ^1.0.4
  rxdart: ^0.27.3
  provider: ^6.0.2
  google_fonts: ^2.1.0
  uuid: ^3.0.6
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  screenshot: ^1.2.3
  share_plus: ^4.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  build_runner: ^2.2.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/